### ISSUE TITLE
wackamole csv data output

### ISSUE THREAD

**Issue by scottbateman** [ncphillips/crowdstudy_whack_a_mole#1]
Headers should be 

id, feedback_type, round, trial, time, errors, moleclicked, distance, target_size
- moleclicked: will be 1 or 0... 1 if clicked, 0 if not
- errors: count of missed clicks
- distance is dynamic: distance between the point the mouse is at to the centre of the mole at the moment the mole first appears.

**Comment by ncphillips** [comment]
Would we also want the distance between the mole centre and the mouse at the end?

**Comment by scottbateman** [comment]
Only if it is really easy. Probably won't use it.

On 5 August 2015 at 13:48, NCPhillips notifications@github.com wrote:

> Would we also want the distance between the mole centre and the mouse at
> the end?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ncphillips/crowdstudy_whack_a_mole/issues/1#issuecomment-128067807
> .

## 

Scott Bateman, PhD
Assistant Professor

Faculty of Computer Science
University of New Brunswick
scottbateman.ca

**Comment by ncphillips** [comment]
Does this look like it makes sense for the distance? I'm getting really big answers....

```
// Mole Dimensions
var mole_width = (round.mole_rect.right- round.mole_rect.left);
var mole_height = (round.mole_rect.bottom - round.mole_rect.top);

// Mole Center Coordinates
var mx = round.mole_rect.left + (mole_width/2);
var my = round.mole_rect.top + (mole_height/2);

// Mouse Deltas
var dx = mx - round.mouse_start[0];
var dy = my - round.mouse_start[1];

// Distance
var distance = Math.sqrt((dx*dx) + (dy*dy)); 
```

EDIT:

Turns our `round.mole_rect.*` values are being stored as strings in MongoDB. It was concatenating them instead of adding them.. Figured out what to do for the subtraction though....Javascript.

**Comment by scottbateman** [comment]
looks good

**Comment by ncphillips** [comment]
https://github.com/ncphillips/crowdstudy_whack_a_mole/commit/e6d26dfa8c74a11f87e3ef610ed94dbca3b41a93
